### ISSUE TITLE
Add "type" attribute to jawr:script tag

### ISSUE THREAD

**Issue by donv** [ic3fox/jawr#12]
Currently the jawr:script tag sets `type="text/javascript"`.  This is a good default.

We are trying to use JAWR to package JSX files by turning off JSMin and serving our JSX files as a bundle.  This is failing since the jawr script tag sets `text/javascript` instead of `text/babel` as the script type.

```html
<jawr:script src="/bundle/jsx_content.js"/>
```

We can get it working by hard-coding the tag, but then the hash part of the path to the bundle must be manually updated when the content changes.

```HTML
<script type="text/babel" src="/our_app/bundles/gzip_1526605734/bundle/jsx_content.js"></script>
```

A good solution for us would be to add an optional `type` attribute to the `jawr:script` tag like this:

```html
<jawr:script type="text/babel" src="/bundle/jsx_content.js"/>
```

The relevant part of our jawr.properties:

```ini
jawr.js.bundle.searchForm.mappings=/jsx/searchForm.js
jawr.js.bundle.searchForm.bundlepostprocessors=none
jawr.js.bundle.userInput.mappings=/jsx/userInput.js
jawr.js.bundle.userInput.bundlepostprocessors=none

jawr.js.bundle.jsx_content.id=/bundle/jsx_content.js
jawr.js.bundle.jsx_content.composite=true
jawr.js.bundle.jsx_content.child.names=searchForm, userInput
```

Maybe there is another way of doing what we want?

**Comment by ic3fox** [comment]
Hi,

The easiest way is to override the javascript tag to let user set the type attribute.
The JIRA [JAWR-374](https://java.net/jira/browse/JAWR-374) has been created to track this issue.

Cheers,

**Comment by ic3fox** [comment]
This issue has been fixed in the master branch of jawr-main-repo
