### ISSUE TITLE
Url computation issue

### ISSUE THREAD

**Issue by diorcety** [ic3fox/jawr#13]
Hi,

in net.jawr.web.resource.bundle.css.CssImageUrlRewriter#getUrlPath
at line // Check if the URL is absolute, if it is return it as is.

If the url is something like url("/blablabla.css?ou=dfdf")
the return url is url("/blablabla.css")
Is it a normal behaviour?

**Comment by ic3fox** [comment]
Hi diocerty,

Sorry for the late reply.
This is the current behaviour.
The point is that the URL is rewritten to use  the hash of the CSS file.
Can you explain me what is the purpose of the parameter?
Does it make sense to keep it with the rewritten URL.

Cheers,

**Comment by diorcety** [comment]
Hi,
I understand your question, but i don't see why this is a correct behavior to remove the parameter, especially regarding the comment just before "// Check if the URL is absolute, if it is return it as is."
Which is not the case actually

**Comment by ic3fox** [comment]
Hi diorcety 

You're totally right.
I've missed the fact that it was a absolute path URL so it will not be rewritten.
I've created the JIRA [JAWR-380](https://java.net/jira/browse/JAWR-380) to follow this issue.

Thanks for the pull request.

Cheers,
icefox

**Comment by ic3fox** [comment]
Hi

This issue has been fixed in the main repository.

Thanks for reporting this issue and providing the patch.

Cheers,
