### ISSUE TITLE
replace asual less-engine with less4j

### ISSUE THREAD

**Issue by tveimo** [ic3fox/jawr#6]
Work seems to have come to a halt with the asual less-engine (and less-servlet). Would it be an idea to migrate to less4j instead? https://github.com/SomMeri/less4j

**Comment by ic3fox** [comment]
Hi,

The JIRA  [JAWR-353](https://java.net/jira/browse/JAWR-353) has been created to follow this issue.
It will be delivered with the next version of Jawr (version 3.8)

Cheers,

**Comment by ic3fox** [comment]
Thanks for reporting this issue.
It has been fixed in the master branch of https://github.com/ic3fox/jawr-main-repo.
It will be syncrhonized soon.

Cheers,
