### ISSUE TITLE
Implement new pure java sass generation using vaadin sass compiler

### ISSUE THREAD

**Issue by tveimo** [ic3fox/jawr#8]
The vaadin sass compiler is a pure java implementation of the sass compiler, see https://github.com/vaadin/sass-compiler

**Comment by ic3fox** [comment]
Hi,

The JIRA [JAWR-354](https://java.net/jira/browse/JAWR-354) has been created to track this new feature request.

Cheers,

**Comment by ic3fox** [comment]
Hi,

This issue has been fixed in the master branch of https://github.com/ic3fox/jawr-main-repo

Cheers
