### ISSUE TITLE
Implement resource fingerprinting

### ISSUE THREAD

**Issue by tveimo** [ic3fox/jawr#9]
It would be nice to append a md5 or timestamp based fingerprint to resources, so that they can have a cache expiry date far in the future and still ensure being reloaded if the resource content changes.

**Comment by ic3fox** [comment]
Hi,

Can you elaborate your request?
Jawr already adds *finderprint* to generated bundle. (like : http://myapp/gzip_32156421/bundle.js )
Jawr also generates *fingerprint* to binary resource defined in CSS resources using MD5.

Can you explain me what you would like to be implemented?

Cheers,

**Comment by tveimo** [comment]
Sorry, I must not have looked closely enough. I'll try it out.
